Implement new `NeptuneLogger`
neptune-ai/pytorch-lightning pull request #3
Opened 2021-03-31 14:31 UTC by shnela

2021-04-01 10:34 UTC, PiotrJander requested changes

2021-04-01 10:34 UTC, PiotrJander commented on pytorch_lightning/loggers/neptune.py
> +            **neptune_run_kwargs):
Did you have any criteria on which neptune.new.init keyword params to include and which to treat generically as `neptune_run_kwargs`? (other than Mycek's spec)

2021-04-01 10:34 UTC, PiotrJander commented on pytorch_lightning/loggers/neptune.py
> +        return state
This was the case in the old domain, are we sure it is also the case in the new domain? Have we tested that everything else can be pickled?

2021-04-01 10:34 UTC, PiotrJander commented on pytorch_lightning/loggers/neptune.py
> +        return self.experiment
I would do it the other way: move logic from the `experiment` property to here and treat the `experiment` property as an alias for the `run` property

2021-04-01 11:30 UTC, shnela commented on pytorch_lightning/loggers/neptune.py
> +    LOGGER_JOIN_CHAR = '-'
I wasn't sure that it was the place for `/` seprator, @Herudaio  agreed, will be changed.

2021-04-01 12:19 UTC, shnela commented on pytorch_lightning/loggers/neptune.py
> +            **neptune_run_kwargs):
* Mycek's spec
* tests of `NeptuneLegacyLogger`
* adapted [example](https://gist.github.com/shnela/0470378ac39066dc8049fc7ecacc52d9) @Herudaio will review that

2021-04-01 13:12 UTC, shnela commented on pytorch_lightning/loggers/neptune.py
> +    from neptune import new as neptune_alpha
right

2021-04-01 13:15 UTC, shnela commented on pytorch_lightning/loggers/neptune.py
> +    """
I think that we should do it in separate MR, that's why I've created `dev/update_neptune_logger` branch.

2021-04-01 14:02 UTC, shnela commented on pytorch_lightning/loggers/neptune.py
> +    neptune_alpha, Run = None, None
Yes, I'll have to implement it here or move this code to our repo if pytorch maintainers agree on that:
https://github.com/PyTorchLightning/pytorch-lightning/discussions/6787

2021-04-01 17:45 UTC, shnela commented on pytorch_lightning/loggers/neptune.py
> +        return state
Yes, it's required. We can't pickle `Run` object because of unpickleable `NeptuneAuthenticator`.
Everything else is fine.

2021-04-02 08:38 UTC, Herudaio commented on pytorch_lightning/loggers/neptune.py
> +            **neptune_run_kwargs):
Let's drop `offline_mode`. In Legacy Logger it was similar to new "debug", not new offline mode. We have the mode in kwargs and we can re-add it at a later date if needed. 
The rest looks good.

2021-04-02 11:58 UTC, merged